import "./globals.css";
import { Nunito_Sans } from "next/font/google";
import { AuthProvider } from "@/context/authContext";

const inter = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
import ToastContainer from "@/services/toast/ToastContainer";
import "material-icons/iconfont/material-icons.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
