import './globals.css';
import { Inter } from 'next/font/google';
import { AuthProvider } from '@/context/authContext';

const inter = Inter({ subsets: ['latin'] })
import ToastContainer from '@/services/toast/ToastContainer';
import "material-icons/iconfont/material-icons.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
